### ISSUE TITLE
DNA molecuul van papier

### ISSUE THREAD

**Issue by CarmenIJsebaart** [DIYbioGroningen/BioCourse#5]
http://www.csiro.au/en/Education/DIY-science/Biology/DNA-model

**Comment by JornPrengerFormeel** [comment]
Zou mij heel leuk lijken.

**Comment by richelbilderbeek** [comment]
Info over DNA alignments: http://slideplayer.com/slide/2490857/

**Comment by richelbilderbeek** [comment]
Hoppa, die gaan we morgen bouwen!

**Comment by richelbilderbeek** [comment]
Hij is erg gaaf geworden...
